### ISSUE TITLE
bluez ./configure ... fails to install bluez package 

### ISSUE THREAD

**Issue by anneranch** [rkresha/oref0#6]
I am following README  downloaded from www.bluez.org and I am unable to verify "bluez" install  - using dpkg --list . 

The instructions are little  unclear as far as building a library I need to have to be able to implement bluetooth in my C++ code. 

I have no issue do "apt install bluez" from Ubuntu repository, but I NEED to be able to install for selected architecture - using --host=.
Am I using wrong resource?

**Comment by rkresha** [comment]
This is, unfortunately, the wrong venue for your question.
